<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Request a Quote',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
             buttons: []
        }}">
    <div class="content">
        <form class="quote_details"
          action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
          id="feedback-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset"> 
           <div class="field required">
                <label class="label" for="quote_name">
                    <span>
                        <?= $block->escapeHtml(__('Quote Name')) ?>
                    </span>
                </label>
                <div class="control">
                    <input name="quote_name" id="quote_name"
                           title="<?= $block->escapeHtmlAttr(__('Quote Name')) ?>" 
                           class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div> 
            
            <div class="field required">
                <label class="label" for="quote_name">
                    <span>
                        <?= $block->escapeHtml(__('Leave your comment here')) ?>
                    </span>
                </label>
                <div class="control">
                    <textarea name="message" id="message"
                              title="<?= $block->escapeHtmlAttr(__('Leave your comment here')) ?>"
                              class="text-area" cols="5" rows="3" data-validate="{required:true}">
                    </textarea>
                </div>
            </div> 
        </fieldset>
            
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                        class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit a Quote')) ?></span>
                </button>
            </div>
        </div>            
    </form>
    </div>
</div>

<div id="click-section" class="click-section">
    <button type="button" class="action primary" data-trigger="trigger">
        <span data-bind="i18n: 'Request a Quote'">            
        </span>
    </button>
</div>